// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDsAPL_H3ejEDY2fcMpa75o2X0K3cytiY',
    appId: '1:484421635706:web:50e5a16772c15043f8f5c3',
    messagingSenderId: '484421635706',
    projectId: 'feedback-app-6e7b4',
    authDomain: 'feedback-app-6e7b4.firebaseapp.com',
    storageBucket: 'feedback-app-6e7b4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfPDQ34lO65ThUyZVcamkOFnGXpYm5kxk',
    appId: '1:484421635706:android:8639da78bdf5c70cf8f5c3',
    messagingSenderId: '484421635706',
    projectId: 'feedback-app-6e7b4',
    storageBucket: 'feedback-app-6e7b4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMn2XJ0l1eeBatx6mI-NIbdgliig_HEjo',
    appId: '1:484421635706:ios:aa9d07074af487b6f8f5c3',
    messagingSenderId: '484421635706',
    projectId: 'feedback-app-6e7b4',
    storageBucket: 'feedback-app-6e7b4.firebasestorage.app',
    iosBundleId: 'com.example.feedbackApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMn2XJ0l1eeBatx6mI-NIbdgliig_HEjo',
    appId: '1:484421635706:ios:aa9d07074af487b6f8f5c3',
    messagingSenderId: '484421635706',
    projectId: 'feedback-app-6e7b4',
    storageBucket: 'feedback-app-6e7b4.firebasestorage.app',
    iosBundleId: 'com.example.feedbackApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDsAPL_H3ejEDY2fcMpa75o2X0K3cytiY',
    appId: '1:484421635706:web:34b3c919980e8c42f8f5c3',
    messagingSenderId: '484421635706',
    projectId: 'feedback-app-6e7b4',
    authDomain: 'feedback-app-6e7b4.firebaseapp.com',
    storageBucket: 'feedback-app-6e7b4.firebasestorage.app',
  );
}
